services:
  astro:
    build: .
    container_name: astro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.astro.rule=Host(`crista-desuraune.fr`) || Host(`www.crista-desuraune.fr`)"
      - "traefik.http.routers.astro.entrypoints=websecure"
      - "traefik.http.routers.astro.tls=true"
      - "traefik.http.routers.astro.tls.certresolver=myresolver"
      - "traefik.http.services.astro.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true