services:
  astro:
    container_name: astro
    restart: unless-stopped
    build:  .
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - "traefik.http.routers.astro.rule=Host(`crista-desuraune.fr`) || Host(`crista-desuraune.fr`)"
      - "traefik.http.routers.astro.entrypoints=websecure"
      - "traefik.http.routers.owguesser.tls.certresolver=letsencrypt"
      - "traefik.http.services.owguesser.loadbalancer.server.port=80"


networks:
  traefik:
    external: true