services:

  astro:
    container_name: astro
    build: .
    restart: unless-stopped
    ports:
      - "4321:4321"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`portfolio.crista-desuraune.fr`)"
      - "traefik.http.routers.astro.entrypoints=web"
      - "traefik.http.services.astro.loadbalancer.server.port=4321"
  
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Let's Encrypt (désactivé par défaut)
      # - "--certificatesresolvers.le.acme.httpchallenge=true"
      # - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.le.acme.email=you@example.com"
      # - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    external: false